title: Divyasri Vemula
logo: /assets/img/profile_circle.png
description: >
  Software Engineer passionate about building AI-powered, cloud-native applications. 
  Skilled in React, LangChain, Google Cloud, and full stack development. 
  Always exploring, building, and solving real-world problems with code.

show_downloads: false
theme: jekyll-theme-minimal
